stderr of test 'ID.1267018.swallowed_error_messages-2` in directory 'tests/BugsViaSourceforge` itself:


# 19:03:55 >  
# 19:03:55 >  Mtimeout -timeout 60 Mserver "--config=/net/corona.ins.cwi.nl/export/scratch0/manegold/Monet/Testing/Current/.GNU.64.64.d.--enable-debug.PREFIX./etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/net/corona.ins.cwi.nl/export/scratch0/manegold/Monet/Testing/Current/.GNU.64.64.d.--enable-debug.PREFIX./lib/MonetDB:/net/corona.ins.cwi.nl/export/scratch0/manegold/Monet/Testing/Current/.GNU.64.64.d.--enable-debug.PREFIX./lib/bin" --set "gdk_dbfarm=/net/corona.ins.cwi.nl/export/scratch0/manegold/Monet/Testing/Current/.GNU.64.64.d.--enable-debug.PREFIX./var/MonetDB/dbfarm" --set "sql_logdir=/net/corona.ins.cwi.nl/export/scratch0/manegold/Monet/Testing/Current/.GNU.64.64.d.--enable-debug.PREFIX./var/MonetDB/log" --set mapi_port=34393 --set sql_port=42119 --set xquery_port=55495 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourceforge  < ID.1267018.swallowed_error_messages-2.milS
# 19:03:55 >  


# 19:03:55 >  
# 19:03:55 >  Done.
# 19:03:55 >  

