stdout of test 'error.998332` in directory 'monetdb5/tests/BugDay_2005-10-06_4.9.3` itself:


# 16:36:59 >  
# 16:36:59 >  Mtimeout -timeout 60 Mserver "--config=/ufs/alink/local/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/ufs/alink/local/lib/MonetDB:/ufs/alink/local/lib/bin" --set "gdk_dbfarm=/ufs/alink/local/var/MonetDB/dbfarm" --set "sql_logdir=/ufs/alink/local/var/MonetDB/log" --set mapi_port=39507 --set sql_port=46288 --set xquery_port=57442 --set monet_prompt= --trace --dbname=mTests_tests_BugDay_2005-10-06_4.9.3  < error.998332.milS
# 16:36:59 >  

# MonetDB server v5.9.0, based on kernel v1.27.0
# Serving database 'mTests_tests_BugDay_2005-10-06_4.9.3', using 4 threads
# Compiled for x86_64-unknown-linux-gnu/64bit with 64bit OIDs dynamically linked
# Copyright (c) 1993-July 2008 CWI.
# Copyright (c) August 2008- MonetDB B.V., all rights reserved
# Visit http://monetdb.cwi.nl/ for further information
# Listening for connection requests on mapi:monetdb://eir.ins.cwi.nl:30579/
function user.main():void;
    raise SQLerror := "this is an error ";
end main;
!MALException:user.main[1]:this is an error 
!MALException:user.main[2]:Exception not caught



# 16:36:59 >  
# 16:36:59 >  Done.
# 16:36:59 >  

