stdout of test 'error.998332` in directory 'tests/BugDay_2005-10-06_4.9.3` itself:


# 16:36:59 >  
# 16:36:59 >  Mtimeout -timeout 60 Mserver "--config=/ufs/alink/local/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/ufs/alink/local/lib/MonetDB:/ufs/alink/local/lib/bin" --set "gdk_dbfarm=/ufs/alink/local/var/MonetDB/dbfarm" --set "sql_logdir=/ufs/alink/local/var/MonetDB/log" --set mapi_port=39507 --set sql_port=46288 --set xquery_port=57442 --set monet_prompt= --trace --dbname=mTests_tests_BugDay_2005-10-06_4.9.3  < error.998332.milS
# 16:36:59 >  

# Monet Database Server V4.8.3
# Copyright (c) 1993-2005, CWI. All rights reserved.
# Compiled for x86_64-redhat-linux-gnu/64bit with 32bit OIDs; dynamically linked.
# Visit http://monetdb.cwi.nl/ for further information.
#  raise SQLerror:= "this is an error ";
#
function user.main():void;	# 0  (main:void)
    raise SQLerror := "this is an error ";	# 1  (SQLerror:str)<-(_2:str)
end main;	# 2  
!ERROR: MALException:user.main[1]:this is an error 
!ERROR: MALException:user.main[2]:Exception not catched



# 16:36:59 >  
# 16:36:59 >  Done.
# 16:36:59 >  

