stderr of test 'unknown_user` in directory 'src/test/Users` itself:


# 14:12:50 >  
# 14:12:50 >  Mtimeout -timeout 240 Mserver "--config=/ufs/niels/scratch/monetdb/Linux-x86_64/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/ufs/niels/scratch/monetdb/Linux-x86_64/lib/MonetDB4:/ufs/niels/scratch/monetdb/Linux-x86_64/lib/MonetDB4/lib:/ufs/niels/scratch/monetdb/Linux-x86_64/lib/MonetDB4/bin" --set "gdk_dbfarm=/ufs/niels/scratch/monetdb/Linux-x86_64/var/MonetDB4/dbfarm" --set "sql_logdir=/ufs/niels/scratch/monetdb/Linux-x86_64/var/MonetDB4/sql_logs" --set "xquery_logdir=/ufs/niels/scratch/monetdb/Linux-x86_64/var/MonetDB4/xquery_logs" --set mapi_port=31117 --set xrpc_port=42399 --set monet_prompt= --trace "--dbname=mTests_src_test_Users" --dbinit=" module(sql_server);" ; echo ; echo Over..
# 14:12:50 >  


# 14:12:51 >  
# 14:12:51 >  Mtimeout -timeout 120 /usr/bin/python unknown_user.SQL.py unknown_user 
# 14:12:51 >  

!schema authorization error

# 14:12:51 >  
# 14:12:51 >  Done.
# 14:12:51 >  

